name: HubSpot Deploy
author: HubSpot
description: Publish website files to your HubSpot CMS account
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  src_dir:
    description: Directory in project to be published
    required: true
  dest_dir:
    description: Directory in account which project will be published to
    require: true
runs:
  using: "composite"
  steps:
    - name: Install NPM deps
      run: npm install
      shell: bash
    - name: Deploy
      env:
        HUBSPOT_PORTAL_ID: ${{ env.HUBSPOT_PORTAL_ID }}
        HUBSPOT_PERSONAL_ACCESS_KEY: ${{ env.HUBSPOT_PERSONAL_ACCESS_KEY }}
      run: |
        npx hs upload ${{ inputs.src_dir }} ${{ inputs.dest_dir }} --use-env
      shell: bash
