name: HubSpot Deploy
author: HubSpot
description: Publish website files to your HubSpot CMS account
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  src_dir:
    description: Directory in project to be published
    required: true
  dest_dir:
    description: Directory in account which project will be published to
    require: true
