name: HubSpot Deploy
author: HubSpot
description: Publish website files to your HubSpot CMS account
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  src_dir:
    description: Directory in project to be published
    required: true
  dest_dir:
    description: Directory in account which project will be published to
    require: true
  hubspot_portal_id:
    description: Secret
    require: true
  hubspot_personal_access_key:
    description: Secret
    require: true
runs:
  using: "composite"
  steps:
    - name: Install NPM deps
      run: npm install
      shell: bash
    - name: Deploy
      run: |
        npx hs upload ${{ inputs.INPUT_SRC_DIR }} ${{ inputs.INPUT_SRC_DIR }} --use-env
      shell: bash
