defaultPortal: test
portals:
  - name: test
    portalId: 8556214
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CO21qf3ULhIIAA0ADAAA4AEYtp2KBCCvmpMBKO7pDDIZAPkp8YXnsD-k4Kp5UKzFsALxRhWv1MISszogAAAEQQAAAHgAAAAAAAAAAIABAAAAAAAEwADAB2D-_zFCGQD5KfGFOlUzryP0XrhpCpzhdWScvaCMlww
        expiresAt: '2020-10-22T09:36:05.875Z'
    personalAccessKey: >-
      CiRkZGU2YTk2NS0xOTk3LTRhNmYtOTNmZC02MWNhYjlkYmI2MTAQtp2KBBivmpMBKhkABeaRguStfDtqcNTxM6EAMcU35NYFn_7B
