on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: HubSpot Deploy Action
        uses: ./
        with:
          src_dir: resources
          des_dir: resources
        env:
          HUBSPOT_PORTAL_ID: ${{ secrets.HubSpotPortalId }}
          HUBSPOT_PERSONAL_ACCESS_KEY: ${{ secrets.HubSpotPersonalAccessKey }}
